### ISSUE TITLE
Incompatibility Issue

### ISSUE THREAD

**Issue by axelex** [Devitek/laravel-yaml-configuration#12]
I've added the laravel support like this in app/http/Kernel.php:

<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
        'Illuminate\Cookie\Middleware\EncryptCookies',
        'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
        'Illuminate\Session\Middleware\StartSession',
        'Illuminate\View\Middleware\ShareErrorsFromSession',
//		'App\Http\Middleware\VerifyCsrfToken', //re-enable if you're disabling JWT
    ];

    /**
     * The application's route middleware.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => 'App\Http\Middleware\Authenticate',
        'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
        'guest' => 'App\Http\Middleware\RedirectIfAuthenticated',
        'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
        'jwt.refresh' => \Tymon\JWTAuth\Middleware\RefreshToken::class,
    ];

    protected function bootstrappers()
    {
        return array_merge($this->bootstrappers, [\Devitek\Core\Config\LoadYamlConfiguration::class]);
    }
}

and I'm getting this error:

ErrorException in LoadYamlConfiguration.php line 38:
Declaration of Devitek\Core\Config\LoadYamlConfiguration::getConfigurationNesting() should be compatible with Illuminate\Foundation\Bootstrap\LoadConfiguration::getConfigurationNesting(Symfony\Component\Finder\SplFileInfo $file, $configPath)

Can you help me?

**Comment by CaporalDead** [comment]
Are you using Laravel 5.1 ?

**Comment by CaporalDead** [comment]
Hmm ok, I see, the API of LoadConfiguration changed between 5.0 and 5.1. Didn't remember why we overrided the getConfigurationNesting which extends the LoadConfiguration class from Laravel.

Can you try to remove the getConfigurationNesting method from Devitek/Core/Config/LoadYamlConfiguration.php and test it again ? Can't test it myself right now. If it's ok then I'll commit an update tomorrow.

**Comment by axelex** [comment]
not really, the method is use in getConfigurationFiles that is also used in loadConfigurationFiles method...

**Comment by axelex** [comment]
ignore my last comment...

**Comment by CaporalDead** [comment]
Can you change your composer.json to use dev-master instead of 2.* and test it again using the configuration shown in the doc ?

**Comment by axelex** [comment]
I've changed the composer.json, I've added the merge of the yaml with the other bootstrappers, and it's the same, it throws me this error when trying to get the info in controller:
Class 'Devitek\Core\Config' not found

**Comment by CaporalDead** [comment]
The class Devitek\Core\Config doesn't exists, you should use the \Devitek\Core\Config\LoadYamlConfiguration::class

**Comment by axelex** [comment]
I know... I tried that too and the only method I can access on LoadYamlConfiguration is 'bootstrap'.
Not sure how I should use that to get the configuration made in config/test.yml in my controller.
