### ISSUE TITLE
Incompatible declaration of getConfigurationNesting() for Laravel 5.1.23

### ISSUE THREAD

**Issue by krom** [Devitek/laravel-yaml-configuration#13]
Declaration of *Illuminate\Foundation\Bootstrap\LoadConfiguration::getConfigurationNesting(Symfony\Component\Finder\SplFileInfo $file, $configPath)* changed at last commit.

See: https://github.com/laravel/framework/commit/b35b3270d23d7f38181e60010dd825cfa5abb4b2

**Error**
Declaration of Devitek\Core\Config\LoadYamlConfiguration::getConfigurationNesting() should be compatible with Illuminate\Foundation\Bootstrap\LoadConfiguration::getConfigurationNesting(Symfony\Component\Finder\SplFileInfo $file, $configPath)

**Comment by CaporalDead** [comment]
OMFG >< sorry @krom wasn't notified for your issues. I'll check it out this week !

**Comment by CaporalDead** [comment]
Updated the code based on your work
