### ISSUE TITLE
Laravel 5.2 dependencies error

### ISSUE THREAD

**Issue by Under-Warz** [Devitek/laravel-yaml-configuration#17]
Hi,

I tried to use your lib with laravel 5.2 (I already use your lib previously with Laravel 4 & 5.0 and everything was good, thx again for this) but when I tried to install it, composer told me 

Problem 1
    - devitek/yaml-configuration 2.2 requires illuminate/foundation 5.* -> no matching package found.
    - devitek/yaml-configuration 2.1 requires illuminate/foundation 5.* -> no matching package found.
    - devitek/yaml-configuration 2.0.1 requires illuminate/foundation 5.* -> no matching package found.
    - devitek/yaml-configuration 2.0 requires illuminate/foundation 5.* -> no matching package found.
    - Installation request for devitek/yaml-configuration 2.* -> satisfiable by devitek/yaml-configuration[2.0, 2.0.1, 2.1, 2.2].

And if I type "composer require devitek/yaml-configuration"

Problem 1
    - Installation request for devitek/yaml-configuration ^3.0 -> satisfiable by devitek/yaml-configuration[3.0].
    - Conclusion: remove symfony/yaml v3.1.1
    - Conclusion: don't install symfony/yaml v3.1.1
    - devitek/yaml-configuration 3.0 requires symfony/yaml 2.*

Any idea ? Thanks again,

**Comment by CaporalDead** [comment]
Hi, thx for your feedback :). Laravel changed the base repository few weeks age, I'll update it this afternoon or to night ! I'll keep you up to date ;).

**Comment by CaporalDead** [comment]
Hi @Under-Warz, I couldn't reproduce this bug, I just installed a fresh copy of Laravel and then I use this command : `composer require devitek/yaml-configuration` which added this to my composer.json file : `"devitek/yaml-configuration": "^3.0"`. Could you plz give me the exact version of Laravel you are using ?

**Comment by CaporalDead** [comment]
You can now use the 3.1 version and everything you should be fine :).

**Comment by Under-Warz** [comment]
Hi Thomas, thanks for your reactivity ;) I'll try it tomorrow at work. I'll keep you in touch

**Comment by Under-Warz** [comment]
@CaporalDead hi, everything's good ;) thank's again

**Comment by CaporalDead** [comment]
You're welcome :)

2016-06-27 16:00 GMT+02:00 Laurent Menu <notifications@github.com>:

> @CaporalDead <https://github.com/CaporalDead> hi, everything's good ;)
> thank's again
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Devitek/laravel-yaml-configuration/issues/17#issuecomment-228753835>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABoGffqdjhAaT1vzu01BUata4xP9Dpcbks5qP9d4gaJpZM4I9jqh>
> .
>



-- 
Thomas SIEFFERT
Ingénieur Informatique

« Le peuple n'a jamais eu autant de pouvoir que sur Internet. »
Valentin Lacambre

« Un grand pouvoir implique de grandes responsabilités. »
Benjamin Parker, Spider Man
________________________________

Adoptez l'éco-attitude.
N'imprimez ce mail que si c'est vraiment nécessaire
