### ISSUE TITLE
Why not to use ServiceProvider?

### ISSUE THREAD

**Issue by mirzap** [Devitek/laravel-yaml-configuration#4]
Thanks for this package, it's exactly what I needed for my project, except I did not want to mess with the core by changing **bootstrap/start.php**. 
I was trying to find the solution to avoid this. Here is what I found.

If you look at **Illuminate/Foundation/start.php** you'll find:

```
$app->instance('config', $config = new Config(
	$app->getConfigLoader(), $env
));
```
which injects Config repository instance into app container. Then I looked at file you overriding **Illuminate\Foundation\Application.php**:

```
public function getConfigLoader()
{
	return new FileLoader(new Filesystem, $this['path'].'/config');
}
```
So, I was thinking why not just override this in ServiceProvider, and then all you need to do is to add your service provider to providers array.

Here is my [YamlServiceProvider](https://github.com/Bosnadev/yaml/blob/master/src/Bosnadev/Yaml/YamlServiceProvider.php)

I can send pull request if you want.

**Comment by CaporalDead** [comment]
Updated to support Laravel 5.1 with an easiest way to use, hope it will be good for you.
