### ISSUE TITLE
Laravel 4.2

### ISSUE THREAD

**Issue by samkitano** [Devitek/laravel-yaml-configuration#7]
I'm using this package on several Laravel 4 applications, and it was working just fine, until I had to make some updates.

Composer is now returning an error:

```
Call to undefined method Devitek\\Core\\Foundation\\Application::configPath()
```

Is there any chance to keep separate versions of the packages for L4 and L5?

Or to tell composer to install the previous version?

I have TONS of yaml translation files, and just the though of reverting them to php is giving me a severe migrane xD

**Comment by samkitano** [comment]
OK, sorry about that.

It turns out the error was from another package which updated to L5 as well, and I also figured out how to tell composer to load previous versions, for both configuration and translation. I had "*" on my composer.json

Totally my bad. Desperation is a nasty lady.

Best regards!

BTW, thanks for this pkg. It's great!

**Comment by CaporalDead** [comment]
No problem you're welcome :).

2015-03-20 15:13 GMT+01:00 samkitano <notifications@github.com>:

> OK, sorry about that.
>
> It turns out the error was from another package which updated to L5 as
> well, and I also figured out how to tell composer to load previous
> versions, for both configuration and translation. I had "*" on my
> composer.json
>
> Totally my bad. Desperation is a nasty lady.
>
> Best regards!
>
> BTW, thanks for this pkg. It's great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Devitek/laravel-yaml-configuration/issues/7#issuecomment-84024537>
> .
>



-- 
Thomas SIEFFERT
Ingénieur Informatique

« Le peuple n'a jamais eu autant de pouvoir que sur Internet. »
Valentin Lacambre

« Un grand pouvoir implique de grandes responsabilités. »
Benjamin Parker, Spider Man
________________________________

Adoptez l'éco-attitude.
N'imprimez ce mail que si c'est vraiment nécessaire
