### ISSUE TITLE
Access level error

### ISSUE THREAD

**Issue by samkitano** [Devitek/laravel-yaml-configuration#8]
Hello!

Just got this issue today while updating an app I'm developing in L5:

```
Fatal error: Access level to Devitek\Core\Config\LoadYamlConfiguration::getConfigurationNesting() must be protected (as in class Illuminate\Foundation\Bootstrap\LoadConfiguration) or weaker in mydisk:\xampp\htdocs\myapp\vendor\devitek\yaml-configuration\src\Devitek\Core\Config\LoadYamlConfiguration.php on line 13
```

in Laravel v5.1.9 with php v5.6.8

Would it be enough to change the function's access from private to protected? I did so, locally, and apparently it's working fine...

**Comment by CaporalDead** [comment]
Hi, thanks for your feedback. I'll check this today.

**Comment by CaporalDead** [comment]
You can update to tag 2.0, I fix the bug and update the way to use the package

**Comment by samkitano** [comment]
That was fast :)

Thanks a lot!


Em Thu, 06 Aug 2015 11:18:26 +0100, Thomas Sieffert  
<notifications@github.com> escreveu:
